#############################################################################
# Makefile for building: SplitQt
# Generated by qmake (3.0) (Qt 5.7.1)
# Project:  SplitQt.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -spec linux-g++-64 CONFIG+=debug CONFIG+=qml_debug -o Makefile SplitQt.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_SQL_LIB -DQT_XML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -m64 -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -m64 -pipe -g -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtSql -isystem /usr/include/x86_64-linux-gnu/qt5/QtXml -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64
QMAKE         = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = SplitQt1.0.0
DISTDIR = /home/rafa/QtProjects/EasyReceipt/.tmp/SplitQt1.0.0
LINK          = g++
LFLAGS        = -m64
LIBS          = $(SUBLIBS) -L/usr/X11R6/lib64 -lQt5Widgets -lQt5Gui -lQt5Sql -lQt5Xml -lQt5Network -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		User.cpp \
		Dialogs/UsersManagerDialog.cpp \
		UserContainer.cpp \
		PayerObserver.cpp \
		Persistence/UserDbInterface.cpp \
		CustomWidget/PayerWidget.cpp \
		CustomWidget/HistoryWidget.cpp \
		Pages/PayersSelection.cpp \
		CustomWidget/SpaceLineEdit.cpp \
		CustomWidget/PredictionLineEdit.cpp \
		Economy/Ticket.cpp \
		Economy/Product.cpp \
		Economy/TicketContainer.cpp \
		Economy/Debt.cpp \
		Pages/CreateTicketWidget.cpp \
		Pages/ManageTicketWidget.cpp \
		Pages/TotalPayout.cpp \
		Persistence/ConfigDbInterface.cpp \
		config.cpp \
		Dialogs/AboutDialog.cpp \
		Version.cpp \
		UpdateManager.cpp \
		Dialogs/UpdateDialog.cpp \
		Dialogs/ConfigDialog.cpp \
		NotesWindow.cpp \
		CustomWidget/SmallButton.cpp \
		Persistence/NotesDbInterface.cpp \
		NoteData.cpp \
		Economy/Payers.cpp \
		Economy/UserAmountCollection.cpp \
		Economy/UserAmount.cpp \
		Economy/PaymentDistribution.cpp \
		Economy/MultiTicketDistribution.cpp \
		Persistence/XmlExporter.cpp \
		Persistence/XmlImporter.cpp \
		Persistence/HtmlExporter.cpp \
		HtmlInterface.cpp \
		UserDbLoader.cpp \
		XmlInterface.cpp \
		TicketLoadedListener.cpp \
		MainWindow.cpp qrc_resources.cpp \
		moc_UsersManagerDialog.cpp \
		moc_PayerObserver.cpp \
		moc_PayerWidget.cpp \
		moc_HistoryWidget.cpp \
		moc_PayersSelection.cpp \
		moc_SpaceLineEdit.cpp \
		moc_PredictionLineEdit.cpp \
		moc_CreateTicketWidget.cpp \
		moc_ManageTicketWidget.cpp \
		moc_TotalPayout.cpp \
		moc_AboutDialog.cpp \
		moc_UpdateManager.cpp \
		moc_UpdateDialog.cpp \
		moc_ConfigDialog.cpp \
		moc_NotesWindow.cpp \
		moc_SmallButton.cpp \
		moc_MainWindow.cpp
OBJECTS       = main.o \
		User.o \
		UsersManagerDialog.o \
		UserContainer.o \
		PayerObserver.o \
		UserDbInterface.o \
		PayerWidget.o \
		HistoryWidget.o \
		PayersSelection.o \
		SpaceLineEdit.o \
		PredictionLineEdit.o \
		Ticket.o \
		Product.o \
		TicketContainer.o \
		Debt.o \
		CreateTicketWidget.o \
		ManageTicketWidget.o \
		TotalPayout.o \
		ConfigDbInterface.o \
		config.o \
		AboutDialog.o \
		Version.o \
		UpdateManager.o \
		UpdateDialog.o \
		ConfigDialog.o \
		NotesWindow.o \
		SmallButton.o \
		NotesDbInterface.o \
		NoteData.o \
		Payers.o \
		UserAmountCollection.o \
		UserAmount.o \
		PaymentDistribution.o \
		MultiTicketDistribution.o \
		XmlExporter.o \
		XmlImporter.o \
		HtmlExporter.o \
		HtmlInterface.o \
		UserDbLoader.o \
		XmlInterface.o \
		TicketLoadedListener.o \
		MainWindow.o \
		qrc_resources.o \
		moc_UsersManagerDialog.o \
		moc_PayerObserver.o \
		moc_PayerWidget.o \
		moc_HistoryWidget.o \
		moc_PayersSelection.o \
		moc_SpaceLineEdit.o \
		moc_PredictionLineEdit.o \
		moc_CreateTicketWidget.o \
		moc_ManageTicketWidget.o \
		moc_TotalPayout.o \
		moc_AboutDialog.o \
		moc_UpdateManager.o \
		moc_UpdateDialog.o \
		moc_ConfigDialog.o \
		moc_NotesWindow.o \
		moc_SmallButton.o \
		moc_MainWindow.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qml_debug.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		SplitQt.pro User.hpp \
		Dialogs/UsersManagerDialog.hpp \
		UserContainer.hpp \
		PayerObserver.hpp \
		Persistence/UserDbInterface.hpp \
		CustomWidget/PayerWidget.hpp \
		CustomWidget/HistoryWidget.hpp \
		Pages/PayersSelection.hpp \
		CustomWidget/SpaceLineEdit.hpp \
		CustomWidget/PredictionLineEdit.hpp \
		Economy/Ticket.hpp \
		Economy/Product.hpp \
		Economy/TicketContainer.hpp \
		Economy/Debt.hpp \
		Pages/CreateTicketWidget.hpp \
		Pages/ManageTicketWidget.hpp \
		Pages/TotalPayout.hpp \
		Persistence/ConfigDbInterface.hpp \
		Config.hpp \
		Dialogs/AboutDialog.hpp \
		Version.hpp \
		UpdateManager.hpp \
		Dialogs/UpdateDialog.hpp \
		Dialogs/ConfigDialog.hpp \
		NotesWindow.hpp \
		CustomWidget/SmallButton.hpp \
		Persistence/NotesDbInterface.hpp \
		NoteData.hpp \
		Economy/Payers.hpp \
		Economy/UserAmountCollection.hpp \
		Economy/UserAmount.hpp \
		Economy/PaymentDistribution.hpp \
		Economy/MultiTicketDistribution.hpp \
		Persistence/XmlExporter.hpp \
		Persistence/XmlImporter.hpp \
		Persistence/HtmlExporter.hpp \
		HtmlInterface.hpp \
		UserDbLoader.hpp \
		XmlInterface.hpp \
		TicketLoadedListener.hpp \
		MainWindow.hpp main.cpp \
		User.cpp \
		Dialogs/UsersManagerDialog.cpp \
		UserContainer.cpp \
		PayerObserver.cpp \
		Persistence/UserDbInterface.cpp \
		CustomWidget/PayerWidget.cpp \
		CustomWidget/HistoryWidget.cpp \
		Pages/PayersSelection.cpp \
		CustomWidget/SpaceLineEdit.cpp \
		CustomWidget/PredictionLineEdit.cpp \
		Economy/Ticket.cpp \
		Economy/Product.cpp \
		Economy/TicketContainer.cpp \
		Economy/Debt.cpp \
		Pages/CreateTicketWidget.cpp \
		Pages/ManageTicketWidget.cpp \
		Pages/TotalPayout.cpp \
		Persistence/ConfigDbInterface.cpp \
		config.cpp \
		Dialogs/AboutDialog.cpp \
		Version.cpp \
		UpdateManager.cpp \
		Dialogs/UpdateDialog.cpp \
		Dialogs/ConfigDialog.cpp \
		NotesWindow.cpp \
		CustomWidget/SmallButton.cpp \
		Persistence/NotesDbInterface.cpp \
		NoteData.cpp \
		Economy/Payers.cpp \
		Economy/UserAmountCollection.cpp \
		Economy/UserAmount.cpp \
		Economy/PaymentDistribution.cpp \
		Economy/MultiTicketDistribution.cpp \
		Persistence/XmlExporter.cpp \
		Persistence/XmlImporter.cpp \
		Persistence/HtmlExporter.cpp \
		HtmlInterface.cpp \
		UserDbLoader.cpp \
		XmlInterface.cpp \
		TicketLoadedListener.cpp \
		MainWindow.cpp
QMAKE_TARGET  = SplitQt
DESTDIR       = 
TARGET        = SplitQt


first: all
####### Build rules

$(TARGET): ui_mainwindow.h ui_aboutform.h ui_config.h ui_finalpayout.h ui_UsersManager.h ui_updatedialog.h ui_ticketpanel.h ui_products.h ui_payersselector.h ui_noteswindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: SplitQt.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qml_debug.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		SplitQt.pro \
		resources.qrc \
		/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Sql.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Xml.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Network.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl
	$(QMAKE) -spec linux-g++-64 CONFIG+=debug CONFIG+=qml_debug -o Makefile SplitQt.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_serialport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qml_debug.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
SplitQt.pro:
resources.qrc:
/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt5Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt5Sql.prl:
/usr/lib/x86_64-linux-gnu/libQt5Xml.prl:
/usr/lib/x86_64-linux-gnu/libQt5Network.prl:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-g++-64 CONFIG+=debug CONFIG+=qml_debug -o Makefile SplitQt.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents resources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents User.hpp Dialogs/UsersManagerDialog.hpp UserContainer.hpp PayerObserver.hpp Persistence/UserDbInterface.hpp CustomWidget/PayerWidget.hpp CustomWidget/HistoryWidget.hpp Pages/PayersSelection.hpp CustomWidget/SpaceLineEdit.hpp CustomWidget/PredictionLineEdit.hpp Economy/Ticket.hpp Economy/Product.hpp Economy/TicketContainer.hpp Economy/Debt.hpp Pages/CreateTicketWidget.hpp Pages/ManageTicketWidget.hpp Pages/TotalPayout.hpp Persistence/ConfigDbInterface.hpp Config.hpp Dialogs/AboutDialog.hpp Version.hpp UpdateManager.hpp Dialogs/UpdateDialog.hpp Dialogs/ConfigDialog.hpp NotesWindow.hpp CustomWidget/SmallButton.hpp Persistence/NotesDbInterface.hpp NoteData.hpp Economy/Payers.hpp Economy/UserAmountCollection.hpp Economy/UserAmount.hpp Economy/PaymentDistribution.hpp Economy/MultiTicketDistribution.hpp Persistence/XmlExporter.hpp Persistence/XmlImporter.hpp Persistence/HtmlExporter.hpp HtmlInterface.hpp UserDbLoader.hpp XmlInterface.hpp TicketLoadedListener.hpp MainWindow.hpp $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp User.cpp Dialogs/UsersManagerDialog.cpp UserContainer.cpp PayerObserver.cpp Persistence/UserDbInterface.cpp CustomWidget/PayerWidget.cpp CustomWidget/HistoryWidget.cpp Pages/PayersSelection.cpp CustomWidget/SpaceLineEdit.cpp CustomWidget/PredictionLineEdit.cpp Economy/Ticket.cpp Economy/Product.cpp Economy/TicketContainer.cpp Economy/Debt.cpp Pages/CreateTicketWidget.cpp Pages/ManageTicketWidget.cpp Pages/TotalPayout.cpp Persistence/ConfigDbInterface.cpp config.cpp Dialogs/AboutDialog.cpp Version.cpp UpdateManager.cpp Dialogs/UpdateDialog.cpp Dialogs/ConfigDialog.cpp NotesWindow.cpp CustomWidget/SmallButton.cpp Persistence/NotesDbInterface.cpp NoteData.cpp Economy/Payers.cpp Economy/UserAmountCollection.cpp Economy/UserAmount.cpp Economy/PaymentDistribution.cpp Economy/MultiTicketDistribution.cpp Persistence/XmlExporter.cpp Persistence/XmlImporter.cpp Persistence/HtmlExporter.cpp HtmlInterface.cpp UserDbLoader.cpp XmlInterface.cpp TicketLoadedListener.cpp MainWindow.cpp $(DISTDIR)/
	$(COPY_FILE) --parents GUI/mainwindow.ui GUI/aboutform.ui GUI/config.ui GUI/finalpayout.ui GUI/UsersManager.ui GUI/updatedialog.ui GUI/ticketpanel.ui GUI/products.ui GUI/payersselector.ui GUI/noteswindow.ui $(DISTDIR)/
	$(COPY_FILE) --parents text.ts $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: resources.qrc \
		/usr/lib/x86_64-linux-gnu/qt5/bin/rcc \
		Resources/icon.png \
		Resources/ticket.png \
		Resources/money.png \
		Resources/tick.png \
		Resources/pencil.png \
		Resources/red-cross.png \
		Resources/file.png \
		Resources/add.png \
		Resources/trash.png \
		Resources/go-next.png \
		Resources/wrench.png \
		Resources/go-back.png \
		Resources/remove.png \
		Resources/floppy.png \
		Resources/avatar.png \
		Resources/note.png
	/usr/lib/x86_64-linux-gnu/qt5/bin/rcc -name resources resources.qrc -o qrc_resources.cpp

compiler_moc_header_make_all: moc_UsersManagerDialog.cpp moc_PayerObserver.cpp moc_PayerWidget.cpp moc_HistoryWidget.cpp moc_PayersSelection.cpp moc_SpaceLineEdit.cpp moc_PredictionLineEdit.cpp moc_CreateTicketWidget.cpp moc_ManageTicketWidget.cpp moc_TotalPayout.cpp moc_AboutDialog.cpp moc_UpdateManager.cpp moc_UpdateDialog.cpp moc_ConfigDialog.cpp moc_NotesWindow.cpp moc_SmallButton.cpp moc_MainWindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_UsersManagerDialog.cpp moc_PayerObserver.cpp moc_PayerWidget.cpp moc_HistoryWidget.cpp moc_PayersSelection.cpp moc_SpaceLineEdit.cpp moc_PredictionLineEdit.cpp moc_CreateTicketWidget.cpp moc_ManageTicketWidget.cpp moc_TotalPayout.cpp moc_AboutDialog.cpp moc_UpdateManager.cpp moc_UpdateDialog.cpp moc_ConfigDialog.cpp moc_NotesWindow.cpp moc_SmallButton.cpp moc_MainWindow.cpp
moc_UsersManagerDialog.cpp: ui_UsersManager.h \
		UserContainer.hpp \
		User.hpp \
		Persistence/UserDbInterface.hpp \
		Config.hpp \
		Version.hpp \
		Dialogs/UsersManagerDialog.hpp \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/rafa/QtProjects/EasyReceipt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Dialogs/UsersManagerDialog.hpp -o moc_UsersManagerDialog.cpp

moc_PayerObserver.cpp: CustomWidget/SpaceLineEdit.hpp \
		PayerObserver.hpp \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/rafa/QtProjects/EasyReceipt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include PayerObserver.hpp -o moc_PayerObserver.cpp

moc_PayerWidget.cpp: CustomWidget/PayerWidget.hpp \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/rafa/QtProjects/EasyReceipt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include CustomWidget/PayerWidget.hpp -o moc_PayerWidget.cpp

moc_HistoryWidget.cpp: Economy/Product.hpp \
		CustomWidget/HistoryWidget.hpp \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/rafa/QtProjects/EasyReceipt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include CustomWidget/HistoryWidget.hpp -o moc_HistoryWidget.cpp

moc_PayersSelection.cpp: Economy/Ticket.hpp \
		Economy/Product.hpp \
		Economy/Debt.hpp \
		Economy/Payers.hpp \
		Economy/UserAmount.hpp \
		Economy/UserAmountCollection.hpp \
		Economy/TicketContainer.hpp \
		Economy/PaymentDistribution.hpp \
		PayerObserver.hpp \
		CustomWidget/SpaceLineEdit.hpp \
		UserContainer.hpp \
		User.hpp \
		Config.hpp \
		Version.hpp \
		ui_payersselector.h \
		Pages/PayersSelection.hpp \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/rafa/QtProjects/EasyReceipt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Pages/PayersSelection.hpp -o moc_PayersSelection.cpp

moc_SpaceLineEdit.cpp: CustomWidget/SpaceLineEdit.hpp \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/rafa/QtProjects/EasyReceipt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include CustomWidget/SpaceLineEdit.hpp -o moc_SpaceLineEdit.cpp

moc_PredictionLineEdit.cpp: UserContainer.hpp \
		User.hpp \
		CustomWidget/PredictionLineEdit.hpp \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/rafa/QtProjects/EasyReceipt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include CustomWidget/PredictionLineEdit.hpp -o moc_PredictionLineEdit.cpp

moc_CreateTicketWidget.cpp: ui_ticketpanel.h \
		Economy/TicketContainer.hpp \
		Economy/Ticket.hpp \
		Economy/Product.hpp \
		Economy/Debt.hpp \
		Economy/Payers.hpp \
		Economy/UserAmount.hpp \
		Economy/UserAmountCollection.hpp \
		Config.hpp \
		Version.hpp \
		UpdateManager.hpp \
		TicketLoadedListener.hpp \
		Pages/CreateTicketWidget.hpp \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/rafa/QtProjects/EasyReceipt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Pages/CreateTicketWidget.hpp -o moc_CreateTicketWidget.cpp

moc_ManageTicketWidget.cpp: ui_products.h \
		CustomWidget/SpaceLineEdit.hpp \
		CustomWidget/PredictionLineEdit.hpp \
		UserContainer.hpp \
		User.hpp \
		CustomWidget/HistoryWidget.hpp \
		Economy/Product.hpp \
		Config.hpp \
		Version.hpp \
		Economy/TicketContainer.hpp \
		Economy/Ticket.hpp \
		Economy/Debt.hpp \
		Economy/Payers.hpp \
		Economy/UserAmount.hpp \
		Economy/UserAmountCollection.hpp \
		Pages/ManageTicketWidget.hpp \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/rafa/QtProjects/EasyReceipt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Pages/ManageTicketWidget.hpp -o moc_ManageTicketWidget.cpp

moc_TotalPayout.cpp: ui_finalpayout.h \
		Economy/TicketContainer.hpp \
		Economy/Ticket.hpp \
		Economy/Product.hpp \
		Economy/Debt.hpp \
		Economy/Payers.hpp \
		Economy/UserAmount.hpp \
		Economy/UserAmountCollection.hpp \
		Economy/MultiTicketDistribution.hpp \
		Economy/PaymentDistribution.hpp \
		Config.hpp \
		Version.hpp \
		Pages/TotalPayout.hpp \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/rafa/QtProjects/EasyReceipt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Pages/TotalPayout.hpp -o moc_TotalPayout.cpp

moc_AboutDialog.cpp: Version.hpp \
		Config.hpp \
		ui_aboutform.h \
		Dialogs/AboutDialog.hpp \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/rafa/QtProjects/EasyReceipt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Dialogs/AboutDialog.hpp -o moc_AboutDialog.cpp

moc_UpdateManager.cpp: Version.hpp \
		UpdateManager.hpp \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/rafa/QtProjects/EasyReceipt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include UpdateManager.hpp -o moc_UpdateManager.cpp

moc_UpdateDialog.cpp: Version.hpp \
		ui_updatedialog.h \
		Dialogs/UpdateDialog.hpp \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/rafa/QtProjects/EasyReceipt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Dialogs/UpdateDialog.hpp -o moc_UpdateDialog.cpp

moc_ConfigDialog.cpp: ui_config.h \
		Persistence/ConfigDbInterface.hpp \
		Config.hpp \
		Version.hpp \
		Dialogs/ConfigDialog.hpp \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/rafa/QtProjects/EasyReceipt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include Dialogs/ConfigDialog.hpp -o moc_ConfigDialog.cpp

moc_NotesWindow.cpp: CustomWidget/SmallButton.hpp \
		Persistence/NotesDbInterface.hpp \
		NoteData.hpp \
		Config.hpp \
		Version.hpp \
		ui_noteswindow.h \
		NotesWindow.hpp \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/rafa/QtProjects/EasyReceipt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include NotesWindow.hpp -o moc_NotesWindow.cpp

moc_SmallButton.cpp: CustomWidget/SmallButton.hpp \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/rafa/QtProjects/EasyReceipt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include CustomWidget/SmallButton.hpp -o moc_SmallButton.cpp

moc_MainWindow.cpp: Dialogs/UsersManagerDialog.hpp \
		ui_UsersManager.h \
		UserContainer.hpp \
		User.hpp \
		Persistence/UserDbInterface.hpp \
		Config.hpp \
		Version.hpp \
		Dialogs/AboutDialog.hpp \
		ui_aboutform.h \
		Dialogs/UpdateDialog.hpp \
		ui_updatedialog.h \
		Dialogs/ConfigDialog.hpp \
		ui_config.h \
		Persistence/ConfigDbInterface.hpp \
		Pages/PayersSelection.hpp \
		Economy/Ticket.hpp \
		Economy/Product.hpp \
		Economy/Debt.hpp \
		Economy/Payers.hpp \
		Economy/UserAmount.hpp \
		Economy/UserAmountCollection.hpp \
		Economy/TicketContainer.hpp \
		Economy/PaymentDistribution.hpp \
		PayerObserver.hpp \
		CustomWidget/SpaceLineEdit.hpp \
		ui_payersselector.h \
		Pages/CreateTicketWidget.hpp \
		ui_ticketpanel.h \
		UpdateManager.hpp \
		TicketLoadedListener.hpp \
		Pages/ManageTicketWidget.hpp \
		ui_products.h \
		CustomWidget/PredictionLineEdit.hpp \
		CustomWidget/HistoryWidget.hpp \
		Pages/TotalPayout.hpp \
		ui_finalpayout.h \
		Economy/MultiTicketDistribution.hpp \
		Persistence/XmlImporter.hpp \
		Persistence/XmlExporter.hpp \
		UserDbLoader.hpp \
		XmlInterface.hpp \
		HtmlInterface.hpp \
		Persistence/HtmlExporter.hpp \
		NotesWindow.hpp \
		CustomWidget/SmallButton.hpp \
		Persistence/NotesDbInterface.hpp \
		NoteData.hpp \
		ui_noteswindow.h \
		MainWindow.hpp \
		/usr/lib/x86_64-linux-gnu/qt5/bin/moc
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/rafa/QtProjects/EasyReceipt -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/6 -I/usr/include/x86_64-linux-gnu/c++/6 -I/usr/include/c++/6/backward -I/usr/lib/gcc/x86_64-linux-gnu/6/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/6/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include MainWindow.hpp -o moc_MainWindow.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_aboutform.h ui_config.h ui_finalpayout.h ui_UsersManager.h ui_updatedialog.h ui_ticketpanel.h ui_products.h ui_payersselector.h ui_noteswindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_aboutform.h ui_config.h ui_finalpayout.h ui_UsersManager.h ui_updatedialog.h ui_ticketpanel.h ui_products.h ui_payersselector.h ui_noteswindow.h
ui_mainwindow.h: GUI/mainwindow.ui \
		/usr/lib/x86_64-linux-gnu/qt5/bin/uic
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic GUI/mainwindow.ui -o ui_mainwindow.h

ui_aboutform.h: GUI/aboutform.ui \
		/usr/lib/x86_64-linux-gnu/qt5/bin/uic
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic GUI/aboutform.ui -o ui_aboutform.h

ui_config.h: GUI/config.ui \
		/usr/lib/x86_64-linux-gnu/qt5/bin/uic
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic GUI/config.ui -o ui_config.h

ui_finalpayout.h: GUI/finalpayout.ui \
		/usr/lib/x86_64-linux-gnu/qt5/bin/uic
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic GUI/finalpayout.ui -o ui_finalpayout.h

ui_UsersManager.h: GUI/UsersManager.ui \
		/usr/lib/x86_64-linux-gnu/qt5/bin/uic
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic GUI/UsersManager.ui -o ui_UsersManager.h

ui_updatedialog.h: GUI/updatedialog.ui \
		/usr/lib/x86_64-linux-gnu/qt5/bin/uic
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic GUI/updatedialog.ui -o ui_updatedialog.h

ui_ticketpanel.h: GUI/ticketpanel.ui \
		/usr/lib/x86_64-linux-gnu/qt5/bin/uic
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic GUI/ticketpanel.ui -o ui_ticketpanel.h

ui_products.h: GUI/products.ui \
		/usr/lib/x86_64-linux-gnu/qt5/bin/uic
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic GUI/products.ui -o ui_products.h

ui_payersselector.h: GUI/payersselector.ui \
		/usr/lib/x86_64-linux-gnu/qt5/bin/uic
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic GUI/payersselector.ui -o ui_payersselector.h

ui_noteswindow.h: GUI/noteswindow.ui \
		/usr/lib/x86_64-linux-gnu/qt5/bin/uic
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic GUI/noteswindow.ui -o ui_noteswindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp MainWindow.hpp \
		Dialogs/UsersManagerDialog.hpp \
		ui_UsersManager.h \
		UserContainer.hpp \
		User.hpp \
		Persistence/UserDbInterface.hpp \
		Config.hpp \
		Version.hpp \
		Dialogs/AboutDialog.hpp \
		ui_aboutform.h \
		Dialogs/UpdateDialog.hpp \
		ui_updatedialog.h \
		Dialogs/ConfigDialog.hpp \
		ui_config.h \
		Persistence/ConfigDbInterface.hpp \
		Pages/PayersSelection.hpp \
		Economy/Ticket.hpp \
		Economy/Product.hpp \
		Economy/Debt.hpp \
		Economy/Payers.hpp \
		Economy/UserAmount.hpp \
		Economy/UserAmountCollection.hpp \
		Economy/TicketContainer.hpp \
		Economy/PaymentDistribution.hpp \
		PayerObserver.hpp \
		CustomWidget/SpaceLineEdit.hpp \
		ui_payersselector.h \
		Pages/CreateTicketWidget.hpp \
		ui_ticketpanel.h \
		UpdateManager.hpp \
		TicketLoadedListener.hpp \
		Pages/ManageTicketWidget.hpp \
		ui_products.h \
		CustomWidget/PredictionLineEdit.hpp \
		CustomWidget/HistoryWidget.hpp \
		Pages/TotalPayout.hpp \
		ui_finalpayout.h \
		Economy/MultiTicketDistribution.hpp \
		Persistence/XmlImporter.hpp \
		Persistence/XmlExporter.hpp \
		UserDbLoader.hpp \
		XmlInterface.hpp \
		HtmlInterface.hpp \
		Persistence/HtmlExporter.hpp \
		NotesWindow.hpp \
		CustomWidget/SmallButton.hpp \
		Persistence/NotesDbInterface.hpp \
		NoteData.hpp \
		ui_noteswindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

User.o: User.cpp User.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o User.o User.cpp

UsersManagerDialog.o: Dialogs/UsersManagerDialog.cpp Dialogs/UsersManagerDialog.hpp \
		ui_UsersManager.h \
		UserContainer.hpp \
		User.hpp \
		Persistence/UserDbInterface.hpp \
		Config.hpp \
		Version.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o UsersManagerDialog.o Dialogs/UsersManagerDialog.cpp

UserContainer.o: UserContainer.cpp UserContainer.hpp \
		User.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o UserContainer.o UserContainer.cpp

PayerObserver.o: PayerObserver.cpp PayerObserver.hpp \
		CustomWidget/SpaceLineEdit.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PayerObserver.o PayerObserver.cpp

UserDbInterface.o: Persistence/UserDbInterface.cpp Persistence/UserDbInterface.hpp \
		Config.hpp \
		Version.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o UserDbInterface.o Persistence/UserDbInterface.cpp

PayerWidget.o: CustomWidget/PayerWidget.cpp CustomWidget/PayerWidget.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PayerWidget.o CustomWidget/PayerWidget.cpp

HistoryWidget.o: CustomWidget/HistoryWidget.cpp CustomWidget/HistoryWidget.hpp \
		Economy/Product.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o HistoryWidget.o CustomWidget/HistoryWidget.cpp

PayersSelection.o: Pages/PayersSelection.cpp Pages/PayersSelection.hpp \
		Economy/Ticket.hpp \
		Economy/Product.hpp \
		Economy/Debt.hpp \
		Economy/Payers.hpp \
		Economy/UserAmount.hpp \
		Economy/UserAmountCollection.hpp \
		Economy/TicketContainer.hpp \
		Economy/PaymentDistribution.hpp \
		PayerObserver.hpp \
		CustomWidget/SpaceLineEdit.hpp \
		UserContainer.hpp \
		User.hpp \
		Config.hpp \
		Version.hpp \
		ui_payersselector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PayersSelection.o Pages/PayersSelection.cpp

SpaceLineEdit.o: CustomWidget/SpaceLineEdit.cpp CustomWidget/SpaceLineEdit.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SpaceLineEdit.o CustomWidget/SpaceLineEdit.cpp

PredictionLineEdit.o: CustomWidget/PredictionLineEdit.cpp CustomWidget/PredictionLineEdit.hpp \
		UserContainer.hpp \
		User.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PredictionLineEdit.o CustomWidget/PredictionLineEdit.cpp

Ticket.o: Economy/Ticket.cpp Economy/Ticket.hpp \
		Economy/Product.hpp \
		Economy/Debt.hpp \
		Economy/Payers.hpp \
		Economy/UserAmount.hpp \
		Economy/UserAmountCollection.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Ticket.o Economy/Ticket.cpp

Product.o: Economy/Product.cpp Economy/Product.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Product.o Economy/Product.cpp

TicketContainer.o: Economy/TicketContainer.cpp Economy/TicketContainer.hpp \
		Economy/Ticket.hpp \
		Economy/Product.hpp \
		Economy/Debt.hpp \
		Economy/Payers.hpp \
		Economy/UserAmount.hpp \
		Economy/UserAmountCollection.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TicketContainer.o Economy/TicketContainer.cpp

Debt.o: Economy/Debt.cpp Economy/Debt.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Debt.o Economy/Debt.cpp

CreateTicketWidget.o: Pages/CreateTicketWidget.cpp Pages/CreateTicketWidget.hpp \
		ui_ticketpanel.h \
		Economy/TicketContainer.hpp \
		Economy/Ticket.hpp \
		Economy/Product.hpp \
		Economy/Debt.hpp \
		Economy/Payers.hpp \
		Economy/UserAmount.hpp \
		Economy/UserAmountCollection.hpp \
		Config.hpp \
		Version.hpp \
		UpdateManager.hpp \
		TicketLoadedListener.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CreateTicketWidget.o Pages/CreateTicketWidget.cpp

ManageTicketWidget.o: Pages/ManageTicketWidget.cpp Pages/ManageTicketWidget.hpp \
		ui_products.h \
		CustomWidget/SpaceLineEdit.hpp \
		CustomWidget/PredictionLineEdit.hpp \
		UserContainer.hpp \
		User.hpp \
		CustomWidget/HistoryWidget.hpp \
		Economy/Product.hpp \
		Config.hpp \
		Version.hpp \
		Economy/TicketContainer.hpp \
		Economy/Ticket.hpp \
		Economy/Debt.hpp \
		Economy/Payers.hpp \
		Economy/UserAmount.hpp \
		Economy/UserAmountCollection.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ManageTicketWidget.o Pages/ManageTicketWidget.cpp

TotalPayout.o: Pages/TotalPayout.cpp Pages/TotalPayout.hpp \
		ui_finalpayout.h \
		Economy/TicketContainer.hpp \
		Economy/Ticket.hpp \
		Economy/Product.hpp \
		Economy/Debt.hpp \
		Economy/Payers.hpp \
		Economy/UserAmount.hpp \
		Economy/UserAmountCollection.hpp \
		Economy/MultiTicketDistribution.hpp \
		Economy/PaymentDistribution.hpp \
		Config.hpp \
		Version.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TotalPayout.o Pages/TotalPayout.cpp

ConfigDbInterface.o: Persistence/ConfigDbInterface.cpp Persistence/ConfigDbInterface.hpp \
		Config.hpp \
		Version.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ConfigDbInterface.o Persistence/ConfigDbInterface.cpp

config.o: config.cpp Config.hpp \
		Version.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o config.o config.cpp

AboutDialog.o: Dialogs/AboutDialog.cpp Dialogs/AboutDialog.hpp \
		Version.hpp \
		Config.hpp \
		ui_aboutform.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AboutDialog.o Dialogs/AboutDialog.cpp

Version.o: Version.cpp Version.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Version.o Version.cpp

UpdateManager.o: UpdateManager.cpp UpdateManager.hpp \
		Version.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o UpdateManager.o UpdateManager.cpp

UpdateDialog.o: Dialogs/UpdateDialog.cpp Dialogs/UpdateDialog.hpp \
		Version.hpp \
		ui_updatedialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o UpdateDialog.o Dialogs/UpdateDialog.cpp

ConfigDialog.o: Dialogs/ConfigDialog.cpp Dialogs/ConfigDialog.hpp \
		ui_config.h \
		Persistence/ConfigDbInterface.hpp \
		Config.hpp \
		Version.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ConfigDialog.o Dialogs/ConfigDialog.cpp

NotesWindow.o: NotesWindow.cpp NotesWindow.hpp \
		CustomWidget/SmallButton.hpp \
		Persistence/NotesDbInterface.hpp \
		NoteData.hpp \
		Config.hpp \
		Version.hpp \
		ui_noteswindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o NotesWindow.o NotesWindow.cpp

SmallButton.o: CustomWidget/SmallButton.cpp CustomWidget/SmallButton.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SmallButton.o CustomWidget/SmallButton.cpp

NotesDbInterface.o: Persistence/NotesDbInterface.cpp Persistence/NotesDbInterface.hpp \
		NoteData.hpp \
		Config.hpp \
		Version.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o NotesDbInterface.o Persistence/NotesDbInterface.cpp

NoteData.o: NoteData.cpp NoteData.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o NoteData.o NoteData.cpp

Payers.o: Economy/Payers.cpp Economy/Payers.hpp \
		Economy/UserAmount.hpp \
		Economy/UserAmountCollection.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Payers.o Economy/Payers.cpp

UserAmountCollection.o: Economy/UserAmountCollection.cpp Economy/UserAmountCollection.hpp \
		Economy/UserAmount.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o UserAmountCollection.o Economy/UserAmountCollection.cpp

UserAmount.o: Economy/UserAmount.cpp Economy/UserAmount.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o UserAmount.o Economy/UserAmount.cpp

PaymentDistribution.o: Economy/PaymentDistribution.cpp Economy/PaymentDistribution.hpp \
		Economy/Ticket.hpp \
		Economy/Product.hpp \
		Economy/Debt.hpp \
		Economy/Payers.hpp \
		Economy/UserAmount.hpp \
		Economy/UserAmountCollection.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PaymentDistribution.o Economy/PaymentDistribution.cpp

MultiTicketDistribution.o: Economy/MultiTicketDistribution.cpp Economy/MultiTicketDistribution.hpp \
		Economy/Debt.hpp \
		Economy/PaymentDistribution.hpp \
		Economy/Ticket.hpp \
		Economy/Product.hpp \
		Economy/Payers.hpp \
		Economy/UserAmount.hpp \
		Economy/UserAmountCollection.hpp \
		Economy/TicketContainer.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MultiTicketDistribution.o Economy/MultiTicketDistribution.cpp

XmlExporter.o: Persistence/XmlExporter.cpp Persistence/XmlExporter.hpp \
		Economy/Ticket.hpp \
		Economy/Product.hpp \
		Economy/Debt.hpp \
		Economy/Payers.hpp \
		Economy/UserAmount.hpp \
		Economy/UserAmountCollection.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o XmlExporter.o Persistence/XmlExporter.cpp

XmlImporter.o: Persistence/XmlImporter.cpp Persistence/XmlImporter.hpp \
		Economy/Ticket.hpp \
		Economy/Product.hpp \
		Economy/Debt.hpp \
		Economy/Payers.hpp \
		Economy/UserAmount.hpp \
		Economy/UserAmountCollection.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o XmlImporter.o Persistence/XmlImporter.cpp

HtmlExporter.o: Persistence/HtmlExporter.cpp Persistence/HtmlExporter.hpp \
		Config.hpp \
		Version.hpp \
		Economy/Ticket.hpp \
		Economy/Product.hpp \
		Economy/Debt.hpp \
		Economy/Payers.hpp \
		Economy/UserAmount.hpp \
		Economy/UserAmountCollection.hpp \
		Economy/PaymentDistribution.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o HtmlExporter.o Persistence/HtmlExporter.cpp

HtmlInterface.o: HtmlInterface.cpp HtmlInterface.hpp \
		Config.hpp \
		Version.hpp \
		Economy/Ticket.hpp \
		Economy/Product.hpp \
		Economy/Debt.hpp \
		Economy/Payers.hpp \
		Economy/UserAmount.hpp \
		Economy/UserAmountCollection.hpp \
		Economy/TicketContainer.hpp \
		Persistence/HtmlExporter.hpp \
		Economy/PaymentDistribution.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o HtmlInterface.o HtmlInterface.cpp

UserDbLoader.o: UserDbLoader.cpp UserDbLoader.hpp \
		Dialogs/UsersManagerDialog.hpp \
		ui_UsersManager.h \
		UserContainer.hpp \
		User.hpp \
		Persistence/UserDbInterface.hpp \
		Config.hpp \
		Version.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o UserDbLoader.o UserDbLoader.cpp

XmlInterface.o: XmlInterface.cpp XmlInterface.hpp \
		Economy/TicketContainer.hpp \
		Economy/Ticket.hpp \
		Economy/Product.hpp \
		Economy/Debt.hpp \
		Economy/Payers.hpp \
		Economy/UserAmount.hpp \
		Economy/UserAmountCollection.hpp \
		Persistence/XmlExporter.hpp \
		Persistence/XmlImporter.hpp \
		Config.hpp \
		Version.hpp \
		TicketLoadedListener.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o XmlInterface.o XmlInterface.cpp

TicketLoadedListener.o: TicketLoadedListener.cpp TicketLoadedListener.hpp \
		Economy/Ticket.hpp \
		Economy/Product.hpp \
		Economy/Debt.hpp \
		Economy/Payers.hpp \
		Economy/UserAmount.hpp \
		Economy/UserAmountCollection.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TicketLoadedListener.o TicketLoadedListener.cpp

MainWindow.o: MainWindow.cpp MainWindow.hpp \
		Dialogs/UsersManagerDialog.hpp \
		ui_UsersManager.h \
		UserContainer.hpp \
		User.hpp \
		Persistence/UserDbInterface.hpp \
		Config.hpp \
		Version.hpp \
		Dialogs/AboutDialog.hpp \
		ui_aboutform.h \
		Dialogs/UpdateDialog.hpp \
		ui_updatedialog.h \
		Dialogs/ConfigDialog.hpp \
		ui_config.h \
		Persistence/ConfigDbInterface.hpp \
		Pages/PayersSelection.hpp \
		Economy/Ticket.hpp \
		Economy/Product.hpp \
		Economy/Debt.hpp \
		Economy/Payers.hpp \
		Economy/UserAmount.hpp \
		Economy/UserAmountCollection.hpp \
		Economy/TicketContainer.hpp \
		Economy/PaymentDistribution.hpp \
		PayerObserver.hpp \
		CustomWidget/SpaceLineEdit.hpp \
		ui_payersselector.h \
		Pages/CreateTicketWidget.hpp \
		ui_ticketpanel.h \
		UpdateManager.hpp \
		TicketLoadedListener.hpp \
		Pages/ManageTicketWidget.hpp \
		ui_products.h \
		CustomWidget/PredictionLineEdit.hpp \
		CustomWidget/HistoryWidget.hpp \
		Pages/TotalPayout.hpp \
		ui_finalpayout.h \
		Economy/MultiTicketDistribution.hpp \
		Persistence/XmlImporter.hpp \
		Persistence/XmlExporter.hpp \
		UserDbLoader.hpp \
		XmlInterface.hpp \
		HtmlInterface.hpp \
		Persistence/HtmlExporter.hpp \
		NotesWindow.hpp \
		CustomWidget/SmallButton.hpp \
		Persistence/NotesDbInterface.hpp \
		NoteData.hpp \
		ui_noteswindow.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MainWindow.o MainWindow.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

moc_UsersManagerDialog.o: moc_UsersManagerDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_UsersManagerDialog.o moc_UsersManagerDialog.cpp

moc_PayerObserver.o: moc_PayerObserver.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_PayerObserver.o moc_PayerObserver.cpp

moc_PayerWidget.o: moc_PayerWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_PayerWidget.o moc_PayerWidget.cpp

moc_HistoryWidget.o: moc_HistoryWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_HistoryWidget.o moc_HistoryWidget.cpp

moc_PayersSelection.o: moc_PayersSelection.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_PayersSelection.o moc_PayersSelection.cpp

moc_SpaceLineEdit.o: moc_SpaceLineEdit.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_SpaceLineEdit.o moc_SpaceLineEdit.cpp

moc_PredictionLineEdit.o: moc_PredictionLineEdit.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_PredictionLineEdit.o moc_PredictionLineEdit.cpp

moc_CreateTicketWidget.o: moc_CreateTicketWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_CreateTicketWidget.o moc_CreateTicketWidget.cpp

moc_ManageTicketWidget.o: moc_ManageTicketWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ManageTicketWidget.o moc_ManageTicketWidget.cpp

moc_TotalPayout.o: moc_TotalPayout.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_TotalPayout.o moc_TotalPayout.cpp

moc_AboutDialog.o: moc_AboutDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_AboutDialog.o moc_AboutDialog.cpp

moc_UpdateManager.o: moc_UpdateManager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_UpdateManager.o moc_UpdateManager.cpp

moc_UpdateDialog.o: moc_UpdateDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_UpdateDialog.o moc_UpdateDialog.cpp

moc_ConfigDialog.o: moc_ConfigDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ConfigDialog.o moc_ConfigDialog.cpp

moc_NotesWindow.o: moc_NotesWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_NotesWindow.o moc_NotesWindow.cpp

moc_SmallButton.o: moc_SmallButton.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_SmallButton.o moc_SmallButton.cpp

moc_MainWindow.o: moc_MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MainWindow.o moc_MainWindow.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

